export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_METHOD_REQUEST = "ORDER_PAY_METHOD_REQUEST";
export const ORDER_PAY_METHOD_SUCCESS = "ORDER_PAY_METHOD_SUCCESS";
export const ORDER_PAY_METHOD_FAIL = "ORDER_PAY_METHOD_FAIL";
export const ORDER_PAY_METHOD_RESET = "ORDER_PAY_METHOD_RESET";

export const ORDER_SEND_PAYMENT_REQUEST = "ORDER_SEND_PAYMENT_REQUEST";
export const ORDER_SEND_PAYMENT_SUCCESS = "ORDER_SEND_PAYMENT_SUCCESS";
export const ORDER_SEND_PAYMENT_FAIL = "ORDER_SEND_PAYMENT_FAIL";
export const ORDER_SEND_PAYMENT_RESET = "ORDER_SEND_PAYMENT_RESET";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

export const LOGGED_USER_ORDERS_REQUEST = "LOGGED_USER_ORDERS_REQUEST";
export const LOGGED_USER_ORDERS_SUCCESS = "LOGGED_USER_ORDERS_SUCCESS";
export const LOGGED_USER_ORDERS_FAIL = "LOGGED_USER_ORDERS_FAIL";
export const LOGGED_USER_ORDERS_RESET = "LOGGED_USER_ORDERS_RESET";

export const ADMIN_ORDERS_LIST_REQUEST = "ADMIN_ORDERS_LIST_REQUEST";
export const ADMIN_ORDERS_LIST_SUCCESS = "ADMIN_ORDERS_LIST_SUCCESS";
export const ADMIN_ORDERS_LIST_FAIL = "ADMIN_ORDERS_LIST_FAIL";
export const ADMIN_ORDERS_LIST_RESET = "ADMIN_ORDERS_LIST_RESET";
