export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const LOGGED_USER_ORDERS_SUCCESS = "LOGGED_USER_ORDERS_SUCCESS";
export const LOGGED_USER_ORDERS_REQUEST = "LOGGED_USER_ORDERS_REQUEST";
export const LOGGED_USER_ORDERS_FAIL = "LOGGED_USER_ORDERS_FAIL";
export const LOGGED_USER_ORDERS_RESET = "LOGGED_USER_ORDERS_RESET";
